export const ADD_INGREDIENT='ADD_INGREDIENT'
export const DELETE_INGREDIENT='DELETE_INGREDIENT'
export const SET_DATA="SET_DATA"
export const ERROR="ERROR"

export const PURCHASE_SUCCESS="PURCHASE_SUCCESS"
export const PURCHASE_FAILED="PURCHASE_FAILED"
export const PURCHASE_LOADING="PURCHASE_LOADING"
export const PURCHASE_INIT="PURCHASE_INIT"
export const SET_ORDERS="SET_ORDERS"

export const SET_AUTH="SET_AUTH"
export const LOGIN_ERROR="LOGIN_ERROR"
export const RESET_LOGIN_ERROR="RESET_LOGIN_ERROR"