export const ADD_INGREDIENT='ADD_INGREDIENT'
export const DELETE_INGREDIENT='DELETE_INGREDIENT'
export const SET_DATA="SET_DATA"
export const ERROR="ERROR"

export const PURCHASE_SUCCESS="PURCHASE_SUCCESS"
export const PURCHASE_FAILED="PURCHASE_FAILED"